// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTxtmessageChange();
void onXbeeStrChange();
void onMaxTempChange();
void onMinTempChange();
void onTempSaloonChange();
void onTempWardrobe2Change();
void onLightSwitchChange();

String txtmessage;
String xbee_str;
float humidity;
float maxTemp;
float minTemp;
float temperature;
float temp_saloon;
float temp_wardrobe2;
bool lightSwitch;

void initProperties(){

  ArduinoCloud.addProperty(txtmessage, READWRITE, ON_CHANGE, onTxtmessageChange);
  ArduinoCloud.addProperty(xbee_str, READWRITE, ON_CHANGE, onXbeeStrChange);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(maxTemp, READWRITE, ON_CHANGE, onMaxTempChange);
  ArduinoCloud.addProperty(minTemp, READWRITE, ON_CHANGE, onMinTempChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp_saloon, READWRITE, ON_CHANGE, onTempSaloonChange);
  ArduinoCloud.addProperty(temp_wardrobe2, READWRITE, ON_CHANGE, onTempWardrobe2Change);
  ArduinoCloud.addProperty(lightSwitch, READWRITE, ON_CHANGE, onLightSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
